files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  function-name-format:
    - 1
    - convention: camelcase
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 1
    - size: 4
  mixin-name-format: 1
  nesting-depth:
    - 1
    - max-depth: 4
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  space-after-colon: 1
  variable-name-format:
    - 1
    - convention: "^[a-zA-Z\\-_]+$"
